- name: toverify the data types
  hosts: local
  become: yes
  vars:
    Course: "Azure"
    Duration: 30Days
    Trainer: Harsha
    topics:
    - git
    - maven
    - ansible
    - docker
    tools:
     cloud: AWS
     build: Jenkin
     configuration: ansible
    live: yes
  tasks:
    - name: Displaying data types in ansible
      ansible.builtin.debug:
       msg: "Course can be {{Course}}, It will take {{Duration}} and Traind by{{Trainer}} in this cours {{topics}} along with {{tools}} covered {{is live}}"


