- name: Variables
  hosts: web
  become: yes
  vars:
   Course: "DevOps With Aws"
   Duration: 120hrs
   Trainer: "Shiva"
  tasks:
  - name: Variables Reading
    ansible.builtin.debug:
     msg: "{{Course}}, will take {{Duration}}, and {{Trainer}}"