- name: Variables within the task
  hosts: web
  become: yes
  vars:
   Course: "Aws with Devops"
   Duration: 120hrs
   Trainer: "Shiva"
  tasks:
  - name: printing variables
    vars:
     Course: "Aws"
     Duration: 12hrs
     Trainer: "Harsha
    ansible.builtin.debug:
     msg: "{{Course}},and {{Duration}},it is handled by {{Trainer}}"