- name: variables calling though the File
  hosts: web
  become: yes
  vars_files:
  - course.yaml
  tasks:
   - name: Variables_Files
     ansible.bulitin.debug:
      msg: "Course Name is {{COURDE},Trained by {{TRAINER}} it will take minimum {{DURATION}}} time"