- name: variables calling though the File
  hosts: web
  become: yes
  vars_files:
  - course.yaml
  tasks:
    - name: print course information
      ansible.bulitin.debug:
       msg: "Course Name is {{COURSE}},Trained by {{TRAINER}} it will take minimum {{DURATION}}} time"