- name: Variable with prompt
  hosts: web
  become: yes
  vars_prompt:
   - name: Course
     prompt: Enter the course name
   - name: Duration
     prompt: Enter Corse Duration
   - name: Trainer
     prompt: Enter the Trainer Name

  tasks: 
   - name: Reading the Variables with the prompt
  ansible.builtin.debug:
   msg: "{{Course}},Duration of the Course is {{Duration}} and Treaind BY {{Trainer}}"