- name: Variable with prompt
  hosts: web
  become: yes
  vars_prompt:
   - name: Course
     prompt: Enter the course name
   - name: Duration
     prompt: Enter Corse Duration
   - name: Trainer
     prompt: Enter the Trainer Name

  tasks: 
   - name: Reading the Variables with the prompt
     ansible.builtin.debug:
      msg: "Course Name is {{Course}},Trained by {{Trainer}} it will take minimum {{Duration}} time"